vich_uploader:
    db_driver: orm

    mappings:
       quizz_images:
           uri_prefix: '%quizz_images%'
           upload_destination: '%kernel.project_dir%/public/%quizz_images%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: false
           delete_on_remove: false
